### PR TITLE
Storing Responses in Database

### LINKED ISSUE #31: Storing/Retrieving Survey Responses

### PR DESCRIPTION
**Pull request by Bnortron**
**Initial Commit:**
- Modularized com.example classes (Questions, Responses, Surveys)
- Added Response.java, ResponseController.java, and ResponseRepository.java for storing responses in H2 Response table
- Modified showsurvey.html to use thymeleaf & H2 for displaying Question's instead of external HTML
- Changed name of SurveyQuestion.java to Question.java to simplify naming scheme
- Currently the Question's of a Survey are saved properly and are loaded into showsurvey.html but don't display an input for the user to respond
- Response.java is unlikely to change at this point but ResponseController.java will need to undergo maintenance once input bug is fixed
- viewresponses.html added to show a table of responses to a Survey and should allow a picture of a plot at the bottom of the page in future
- There have been many attempts at trying to save a Response properly, so some classes may have been altered a bit but everything will be cleaned up before final merge

### CODE REVIEW

**Comment by Bnortron** [comment]
**Some screenshots of storing responses testing**

showsurvey.html when the Survey is deactivated:
Response test 1 (Deactivated)

showsurvey.html when the Survey is activated:
Response test 1 (Activated)

H2 Console after submitting responses on an activated Survey:
Response test 1 (H2 Console)

Handling a missing Text Question Response when trying to submit responses:
Response test 2 (Missing Text Response)

Handling a missing MCQ Response when trying to submit responses:
Response test 2 (Missing MCQ Response)

**NOTE: No responses are submitted (and subsequently not stored in the H2 database) if one of the Survey Questions is missing a Response**

**Comment by Bnortron** [comment]
**Some screenshots for storing responses after merging with changes in Main (Updated adding Questions page & styling changes)**

Handling missing Text Response when submitting responses:
Response test 3 (Missing Text Response)

Handling missing MCQ Response when submitting responses:
Response test 3 (Missing MCQ Response)

showsurvey.html page when the Survey is active (before submitting responses):
Response test 3 (Activated)

H2 Console view of "RESPONSE" table after submitting responses for an active Survey (NOTE: I had previously tested adding a single response to a Text Question hence the first Response "Test Response" before the next three responses shown in the above screenshots):
Response Test 3 (H2 Console)

**Comment by Bnortron** [comment]
**For reference this is what some of the other pages look like after merging the storing responses functionality:**

Home page:
Home Page

Create Survey page:
Create Survey

View All Surveys page:
View Surveys

Select Survey page:
Select Survey

**Comment by Bnortron** [comment]
Submitting Responses:
Submitting Responses

View Responses page:
View Responses page

Question Responses page:
Question Responses

**Comment by Bnortron** [comment]
**In addition to the Text Question Response, these are some screenshots showing the view for the other two question types:**

Number Question view:
Question Responses (Number Q)

MCQ Response View:
Question Responses (MCQ)

**Review by Aleksandar-Veselinovic — APPROVED** [review]

**Review by mralifahd — APPROVED** [review]

**Pull request merged**
